name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: git remote add org git@github.com:10M011y01U001n01c101l00e100S11/sixty-six-bbq-admin.git                                                                                                                                               
    - run: git remote set-url --add --push org git@github.com:10M011y01U001n01c101l00e100S11/sixty-six-bbq-admin.git
    - run: git push org    
      shell: bash
      env:
        CI: true
