name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        repo-token: ${{ secrets.PASSWORD }}
        
    - name: Setup SSH Keys and known_hosts
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

    - name: Some task that fetches dependencies
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: ./fetch-deps.sh
        
    - run: npm install
    - run: |
        git config --global user.name chunwarayut
        git config --global user.email warayut2555@gmail.com
    - run: git remote add org git@github.com:10M011y01U001n01c101l00e100S11/sixty-six-bbq-admin.git                                                                                                                                               
    - run: git remote set-url --add --push org git@github.com:10M011y01U001n01c101l00e100S11/sixty-six-bbq-admin.git
    - run: git push org
